-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Retail Superstore sales analysis - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/` (same Spark-dialect SQL that runs locally on DuckDB).
-- MAGIC
-- MAGIC 1. Upload the raw files to the Unity Catalog volume `/Volumes/workspace/da_learn_03/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse (or DBR 13.3+ cluster) and *Run all*.
-- MAGIC 3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.

-- COMMAND ----------

-- Config: change catalog / schema here (and in the dashboard JSON) if needed
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_03;
USE CATALOG workspace;
USE SCHEMA da_learn_03;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging - all columns as STRING (`inferColumnTypes => false`), typing happens in 02

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_orders AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_03/raw/orders.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_returns AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_03/raw/returns.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_people AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_03/raw/people.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; runs on DuckDB via 00_duckdb_compat.sql shims)

CREATE OR REPLACE TABLE cln_people AS
SELECT region, manager_name
FROM (
  SELECT trim(region) AS region, trim(person) AS manager_name,
         ROW_NUMBER() OVER (PARTITION BY lower(trim(region)) ORDER BY trim(person)) AS rn
  FROM stg_people
  WHERE NULLIF(trim(region), '') IS NOT NULL
) p
WHERE rn = 1;

-- COMMAND ----------

-- Returns: the sheet lists one row per returned LINE without line ids -> collapse to one row per order

CREATE OR REPLACE TABLE cln_returns AS
SELECT trim(order_id) AS order_id,
       COUNT(*)       AS return_rows_in_source
FROM stg_returns
WHERE lower(trim(returned)) IN ('yes', 'y', 'true', '1')
  AND NULLIF(trim(order_id), '') IS NOT NULL
GROUP BY trim(order_id);

-- COMMAND ----------

-- Orders (line grain)

CREATE OR REPLACE TABLE cln_orders AS
WITH typed AS (
  SELECT
    TRY_CAST(row_id AS INT)                                   AS row_id,
    upper(trim(order_id))                                     AS order_id,
    TRY_CAST(trim(order_date) AS DATE)                        AS order_date,
    TRY_CAST(trim(ship_date) AS DATE)                         AS ship_date,
    CASE lower(trim(ship_mode))
      WHEN 'same day' THEN 'Same Day' WHEN 'first class' THEN 'First Class'
      WHEN 'second class' THEN 'Second Class' WHEN 'standard class' THEN 'Standard Class'
      ELSE NULLIF(trim(ship_mode), '') END                    AS ship_mode,
    upper(trim(customer_id))                                  AS customer_id,
    trim(customer_name)                                       AS customer_name,
    trim(segment)                                             AS segment,
    trim(country_region)                                      AS country,
    trim(city)                                                AS city,
    trim(state)                                               AS state,
    CASE WHEN TRY_CAST(trim(postal_code) AS DOUBLE) IS NULL THEN NULL
         ELSE lpad(CAST(CAST(TRY_CAST(trim(postal_code) AS DOUBLE) AS INT) AS STRING), 5, '0') END AS postal_code,
    trim(region)                                              AS region,
    upper(trim(product_id))                                   AS product_id,
    trim(category)                                            AS category,
    trim(sub_category)                                        AS sub_category,
    trim(product_name)                                        AS product_name,
    ROUND(TRY_CAST(sales AS DOUBLE), 2)                       AS sales,
    TRY_CAST(quantity AS INT)                                 AS quantity,
    ROUND(TRY_CAST(discount AS DOUBLE), 2)                    AS discount,
    ROUND(TRY_CAST(profit AS DOUBLE), 4)                      AS profit
  FROM stg_orders
), dedup AS (
  SELECT *, ROW_NUMBER() OVER (
    PARTITION BY order_id, product_id, product_name, order_date, ship_date, customer_id, sales, quantity, discount, profit
    ORDER BY row_id) AS dup_rn
  FROM typed
  WHERE row_id IS NOT NULL
), bounds AS (
  SELECT percentile_approx(sales, 0.25) AS q1, percentile_approx(sales, 0.75) AS q3,
         percentile_approx(profit, 0.01) AS p01, percentile_approx(profit, 0.99) AS p99
  FROM dedup WHERE dup_rn = 1
)
SELECT
  d.row_id, d.order_id, d.order_date, d.ship_date,
  datediff(d.ship_date, d.order_date)                         AS ship_days,
  d.ship_mode, d.customer_id, d.customer_name, d.segment, d.country, d.city, d.state,
  d.postal_code, d.region, d.product_id, d.category, d.sub_category, d.product_name,
  d.sales, d.quantity, d.discount, d.profit,
  ROUND(d.sales / NULLIF(1 - d.discount, 0), 2)               AS list_sales,
  ROUND(d.profit / NULLIF(d.sales, 0), 4)                     AS profit_margin,
  CASE WHEN d.discount = 0 THEN '01: 0%'
       WHEN d.discount <= 0.1 THEN '02: 1-10%'
       WHEN d.discount <= 0.2 THEN '03: 11-20%'
       WHEN d.discount <= 0.3 THEN '04: 21-30%'
       WHEN d.discount <= 0.5 THEN '05: 31-50%'
       ELSE '06: >50%' END                                    AS discount_band,
  CASE WHEN d.profit < 0 THEN 1 ELSE 0 END                    AS is_loss_line,
  CASE WHEN r.order_id IS NOT NULL THEN 1 ELSE 0 END          AS returned_flag,
  CASE WHEN d.sales > b.q3 + 3 * (b.q3 - b.q1) THEN 1 ELSE 0 END AS is_sales_outlier_iqr3,
  CASE WHEN d.profit < b.p01 OR d.profit > b.p99 THEN 1 ELSE 0 END AS is_profit_extreme_p1_p99,
  CASE WHEN d.postal_code IS NULL THEN 1 ELSE 0 END           AS dq_missing_postal_code
FROM dedup d
CROSS JOIN bounds b
LEFT JOIN cln_returns r ON d.order_id = r.order_id
WHERE d.dup_rn = 1
  AND d.order_id IS NOT NULL AND d.order_date IS NOT NULL AND d.ship_date IS NOT NULL
  AND d.ship_date >= d.order_date
  AND d.sales IS NOT NULL AND d.sales > 0
  AND d.quantity IS NOT NULL AND d.quantity > 0
  AND d.discount BETWEEN 0 AND 1
  AND d.profit IS NOT NULL;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema (Spark SQL dialect)

CREATE OR REPLACE TABLE dim_date AS
SELECT
  CAST(year(d) * 10000 + month(d) * 100 + day(d) AS INT) AS date_key,
  d AS full_date,
  year(d) AS year,
  quarter(d) AS quarter,
  month(d) AS month,
  concat(CAST(year(d) AS STRING), '-', lpad(CAST(month(d) AS STRING), 2, '0')) AS year_month,
  dayofweek(d) AS day_of_week,
  CASE WHEN dayofweek(d) IN (1, 7) THEN 1 ELSE 0 END AS is_weekend
FROM (SELECT DISTINCT order_date AS d FROM cln_orders) x;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_customer AS
SELECT
  CAST(ROW_NUMBER() OVER (ORDER BY customer_id) AS INT) AS customer_key,
  customer_id, customer_name, segment
FROM (
  SELECT customer_id, MIN(customer_name) AS customer_name, MIN(segment) AS segment
  FROM cln_orders GROUP BY customer_id
) c;

-- COMMAND ----------

-- Product ID is NOT unique in the source (some ids carry 2 names) -> natural key = (product_id, product_name)

CREATE OR REPLACE TABLE dim_product AS
SELECT
  CAST(ROW_NUMBER() OVER (ORDER BY product_id, product_name) AS INT) AS product_key,
  product_id, product_name, category, sub_category
FROM (
  SELECT product_id, product_name, MIN(category) AS category, MIN(sub_category) AS sub_category
  FROM cln_orders GROUP BY product_id, product_name
) p;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_geography AS
SELECT
  CAST(ROW_NUMBER() OVER (ORDER BY g.region, g.state, g.city, g.postal_code) AS INT) AS geo_key,
  g.country, g.region, g.state, g.city, g.postal_code,
  COALESCE(p.manager_name, 'Unassigned') AS regional_manager
FROM (SELECT DISTINCT country, region, state, city, postal_code FROM cln_orders) g
LEFT JOIN cln_people p ON lower(g.region) = lower(p.region);

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_ship_mode AS
SELECT
  CAST(ROW_NUMBER() OVER (ORDER BY CASE ship_mode WHEN 'Same Day' THEN 1 WHEN 'First Class' THEN 2
                                   WHEN 'Second Class' THEN 3 WHEN 'Standard Class' THEN 4 ELSE 5 END) AS INT) AS ship_mode_key,
  ship_mode,
  CASE ship_mode WHEN 'Same Day' THEN 1 WHEN 'First Class' THEN 2
                 WHEN 'Second Class' THEN 3 WHEN 'Standard Class' THEN 4 ELSE 5 END AS service_level_rank
FROM (SELECT DISTINCT ship_mode FROM cln_orders WHERE ship_mode IS NOT NULL) s;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_sales AS
SELECT
  o.row_id AS line_id,
  o.order_id,
  CAST(year(o.order_date) * 10000 + month(o.order_date) * 100 + day(o.order_date) AS INT) AS order_date_key,
  o.order_date,
  o.ship_date,
  c.customer_key,
  p.product_key,
  g.geo_key,
  s.ship_mode_key,
  o.ship_days,
  o.sales,
  o.list_sales,
  o.quantity,
  o.discount,
  o.discount_band,
  o.profit,
  o.profit_margin,
  o.is_loss_line,
  o.returned_flag,
  o.is_sales_outlier_iqr3,
  o.is_profit_extreme_p1_p99
FROM cln_orders o
LEFT JOIN dim_customer c ON o.customer_id = c.customer_id
LEFT JOIN dim_product p ON o.product_id = p.product_id AND o.product_name = p.product_name
LEFT JOIN dim_geography g ON o.region = g.region AND o.state = g.state AND o.city = g.city
     AND COALESCE(o.postal_code, '?') = COALESCE(g.postal_code, '?') AND o.country = g.country
LEFT JOIN dim_ship_mode s ON o.ship_mode = s.ship_mode;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  Business KPI queries (Spark SQL dialect). Each result is materialised as an a_* table

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT
  COUNT(*)                                                         AS order_lines,
  COUNT(DISTINCT order_id)                                         AS orders,
  COUNT(DISTINCT customer_key)                                     AS customers,
  COUNT(DISTINCT product_key)                                      AS products,
  ROUND(SUM(sales), 2)                                             AS total_sales,
  ROUND(SUM(profit), 2)                                            AS total_profit,
  ROUND(100.0 * SUM(profit) / SUM(sales), 2)                       AS profit_margin_pct,
  ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2)                  AS avg_order_value,
  SUM(quantity)                                                    AS units,
  ROUND(AVG(discount) * 100, 2)                                    AS avg_discount_pct,
  ROUND(100.0 * SUM(is_loss_line) / COUNT(*), 2)                   AS loss_line_pct,
  ROUND(-SUM(CASE WHEN profit < 0 THEN profit ELSE 0 END), 2)      AS profit_lost_on_loss_lines,
  ROUND(100.0 * COUNT(DISTINCT CASE WHEN returned_flag = 1 THEN order_id END) / COUNT(DISTINCT order_id), 2) AS order_return_rate_pct,
  ROUND(SUM(CASE WHEN returned_flag = 1 THEN sales ELSE 0 END), 2) AS returned_sales,
  ROUND(AVG(ship_days), 2)                                         AS avg_ship_days,
  MIN(order_date)                                                  AS first_order_date,
  MAX(order_date)                                                  AS last_order_date
FROM fact_sales;

-- COMMAND ----------

-- Q2 Regional profit (with regional manager)

CREATE OR REPLACE TABLE a_region_performance AS
SELECT
  g.region, g.regional_manager,
  COUNT(DISTINCT f.order_id) AS orders,
  ROUND(SUM(f.sales), 2) AS sales,
  ROUND(SUM(f.profit), 2) AS profit,
  ROUND(100.0 * SUM(f.profit) / SUM(f.sales), 2) AS margin_pct,
  ROUND(100.0 * SUM(f.sales) / SUM(SUM(f.sales)) OVER (), 2) AS sales_share_pct,
  ROUND(AVG(f.discount) * 100, 2) AS avg_discount_pct,
  ROUND(100.0 * COUNT(DISTINCT CASE WHEN f.returned_flag = 1 THEN f.order_id END) / COUNT(DISTINCT f.order_id), 2) AS order_return_rate_pct
FROM fact_sales f JOIN dim_geography g ON f.geo_key = g.geo_key
GROUP BY g.region, g.regional_manager;

-- COMMAND ----------

-- Q3 States: most and least profitable

CREATE OR REPLACE TABLE a_state_profit AS
SELECT
  g.region, g.state,
  COUNT(DISTINCT f.order_id) AS orders,
  ROUND(SUM(f.sales), 2) AS sales,
  ROUND(SUM(f.profit), 2) AS profit,
  ROUND(100.0 * SUM(f.profit) / SUM(f.sales), 2) AS margin_pct,
  ROUND(AVG(f.discount) * 100, 2) AS avg_discount_pct,
  RANK() OVER (ORDER BY SUM(f.profit) DESC) AS profit_rank
FROM fact_sales f JOIN dim_geography g ON f.geo_key = g.geo_key
GROUP BY g.region, g.state;

-- COMMAND ----------

-- Q4 Discount impact: margin collapses as discount rises

CREATE OR REPLACE TABLE a_discount_impact AS
SELECT
  discount_band,
  COUNT(*) AS order_lines,
  ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS line_share_pct,
  ROUND(SUM(sales), 2) AS sales,
  ROUND(SUM(profit), 2) AS profit,
  ROUND(100.0 * SUM(profit) / SUM(sales), 2) AS margin_pct,
  ROUND(100.0 * SUM(is_loss_line) / COUNT(*), 2) AS loss_line_pct
FROM fact_sales
GROUP BY discount_band;

-- COMMAND ----------

-- Q5 Discount x category: where discounting destroys profit

CREATE OR REPLACE TABLE a_discount_by_subcategory AS
SELECT
  p.category, p.sub_category,
  COUNT(*) AS order_lines,
  ROUND(SUM(f.sales), 2) AS sales,
  ROUND(SUM(f.profit), 2) AS profit,
  ROUND(100.0 * SUM(f.profit) / SUM(f.sales), 2) AS margin_pct,
  ROUND(AVG(f.discount) * 100, 2) AS avg_discount_pct,
  ROUND(100.0 * SUM(CASE WHEN f.discount > 0 THEN 1 ELSE 0 END) / COUNT(*), 2) AS discounted_line_pct,
  ROUND(100.0 * COUNT(DISTINCT CASE WHEN f.returned_flag = 1 THEN f.order_id END) / COUNT(DISTINCT f.order_id), 2) AS order_return_rate_pct
FROM fact_sales f JOIN dim_product p ON f.product_key = p.product_key
GROUP BY p.category, p.sub_category;

-- COMMAND ----------

-- Q6 Shipping modes: speed, mix and profitability

CREATE OR REPLACE TABLE a_ship_mode AS
SELECT
  s.ship_mode, s.service_level_rank,
  COUNT(DISTINCT f.order_id) AS orders,
  ROUND(100.0 * COUNT(DISTINCT f.order_id) / (SELECT COUNT(DISTINCT order_id) FROM fact_sales), 2) AS order_share_pct,
  ROUND(AVG(f.ship_days), 2) AS avg_ship_days,
  MAX(f.ship_days) AS max_ship_days,
  ROUND(SUM(f.sales), 2) AS sales,
  ROUND(SUM(f.profit), 2) AS profit,
  ROUND(100.0 * SUM(f.profit) / SUM(f.sales), 2) AS margin_pct,
  ROUND(100.0 * COUNT(DISTINCT CASE WHEN f.returned_flag = 1 THEN f.order_id END) / COUNT(DISTINCT f.order_id), 2) AS order_return_rate_pct
FROM fact_sales f JOIN dim_ship_mode s ON f.ship_mode_key = s.ship_mode_key
GROUP BY s.ship_mode, s.service_level_rank;

-- COMMAND ----------

-- Q7 Ship mode x segment order mix

CREATE OR REPLACE TABLE a_ship_mode_segment AS
SELECT
  c.segment, s.ship_mode,
  COUNT(DISTINCT f.order_id) AS orders,
  ROUND(100.0 * COUNT(DISTINCT f.order_id) / SUM(COUNT(DISTINCT f.order_id)) OVER (PARTITION BY c.segment), 2) AS pct_of_segment_orders
FROM fact_sales f
JOIN dim_customer c ON f.customer_key = c.customer_key
JOIN dim_ship_mode s ON f.ship_mode_key = s.ship_mode_key
GROUP BY c.segment, s.ship_mode;

-- COMMAND ----------

-- Q8 Segment performance

CREATE OR REPLACE TABLE a_segment_performance AS
SELECT
  c.segment,
  COUNT(DISTINCT c.customer_key) AS customers,
  COUNT(DISTINCT f.order_id) AS orders,
  ROUND(SUM(f.sales), 2) AS sales,
  ROUND(SUM(f.profit), 2) AS profit,
  ROUND(100.0 * SUM(f.profit) / SUM(f.sales), 2) AS margin_pct,
  ROUND(SUM(f.sales) / COUNT(DISTINCT f.order_id), 2) AS avg_order_value
FROM fact_sales f JOIN dim_customer c ON f.customer_key = c.customer_key
GROUP BY c.segment;

-- COMMAND ----------

-- Q9 Yearly trend with YoY growth

CREATE OR REPLACE TABLE a_yearly_trend AS
SELECT
  year, orders, sales, profit, margin_pct,
  ROUND(100.0 * (sales - LAG(sales) OVER (ORDER BY year)) / LAG(sales) OVER (ORDER BY year), 2) AS sales_yoy_pct,
  ROUND(100.0 * (profit - LAG(profit) OVER (ORDER BY year)) / LAG(profit) OVER (ORDER BY year), 2) AS profit_yoy_pct
FROM (
  SELECT d.year, COUNT(DISTINCT f.order_id) AS orders, ROUND(SUM(f.sales), 2) AS sales,
         ROUND(SUM(f.profit), 2) AS profit, ROUND(100.0 * SUM(f.profit) / SUM(f.sales), 2) AS margin_pct
  FROM fact_sales f JOIN dim_date d ON f.order_date_key = d.date_key
  GROUP BY d.year
) y;

-- COMMAND ----------

-- Q10 Monthly sales and profit

CREATE OR REPLACE TABLE a_monthly_sales AS
SELECT
  d.year_month,
  COUNT(DISTINCT f.order_id) AS orders,
  ROUND(SUM(f.sales), 2) AS sales,
  ROUND(SUM(f.profit), 2) AS profit
FROM fact_sales f JOIN dim_date d ON f.order_date_key = d.date_key
GROUP BY d.year_month;

-- COMMAND ----------

-- Q11 Products that lose the most money

CREATE OR REPLACE TABLE a_top_loss_products AS
SELECT * FROM (
  SELECT
    p.product_name, p.sub_category,
    COUNT(*) AS order_lines,
    ROUND(SUM(f.sales), 2) AS sales,
    ROUND(SUM(f.profit), 2) AS profit,
    ROUND(AVG(f.discount) * 100, 2) AS avg_discount_pct,
    ROW_NUMBER() OVER (ORDER BY SUM(f.profit), p.product_name) AS loss_rank
  FROM fact_sales f JOIN dim_product p ON f.product_key = p.product_key
  GROUP BY p.product_name, p.sub_category
) x WHERE loss_rank <= 10;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  Data-quality evidence (Spark SQL dialect): before/after counts, null rates, issues, assertions

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'orders' AS entity, (SELECT COUNT(*) FROM stg_orders) AS raw_rows,
       (SELECT COUNT(DISTINCT row_id) FROM stg_orders) AS distinct_keys,
       (SELECT COUNT(*) FROM cln_orders) AS clean_rows, 'order line (row_id)' AS grain
UNION ALL SELECT 'returns', (SELECT COUNT(*) FROM stg_returns), (SELECT COUNT(DISTINCT order_id) FROM stg_returns),
       (SELECT COUNT(*) FROM cln_returns), 'returned order'
UNION ALL SELECT 'people', (SELECT COUNT(*) FROM stg_people), (SELECT COUNT(DISTINCT region) FROM stg_people),
       (SELECT COUNT(*) FROM cln_people), 'region'
UNION ALL SELECT 'fact_sales', NULL, NULL, (SELECT COUNT(*) FROM fact_sales), 'order line'
UNION ALL SELECT 'dim_date', NULL, NULL, (SELECT COUNT(*) FROM dim_date), 'order date'
UNION ALL SELECT 'dim_customer', NULL, NULL, (SELECT COUNT(*) FROM dim_customer), 'customer_id'
UNION ALL SELECT 'dim_product', NULL, NULL, (SELECT COUNT(*) FROM dim_product), 'product_id + product_name'
UNION ALL SELECT 'dim_geography', NULL, NULL, (SELECT COUNT(*) FROM dim_geography), 'region/state/city/postal'
UNION ALL SELECT 'dim_ship_mode', NULL, NULL, (SELECT COUNT(*) FROM dim_ship_mode), 'ship mode';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_null_rates AS
SELECT 'orders' AS entity, 'postal_code' AS column_name,
  (SELECT ROUND(100.0 * SUM(CASE WHEN postal_code IS NULL OR trim(postal_code) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_orders) AS raw_null_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN postal_code IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_orders) AS clean_null_pct,
  'kept as NULL (Burlington, VT has no code in source); geography matched on NULL-safe key' AS treatment
UNION ALL SELECT 'orders', 'order_date',
  (SELECT ROUND(100.0 * SUM(CASE WHEN TRY_CAST(order_date AS DATE) IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_orders),
  (SELECT ROUND(100.0 * SUM(CASE WHEN order_date IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_orders),
  'required; unparseable dates dropped'
UNION ALL SELECT 'orders', 'sales',
  (SELECT ROUND(100.0 * SUM(CASE WHEN TRY_CAST(sales AS DOUBLE) IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_orders),
  (SELECT ROUND(100.0 * SUM(CASE WHEN sales IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_orders),
  'required; rounded to 2 dp (float artefacts like 731.9399999999999)'
UNION ALL SELECT 'orders', 'ship_mode',
  (SELECT ROUND(100.0 * SUM(CASE WHEN ship_mode IS NULL OR trim(ship_mode) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_orders),
  (SELECT ROUND(100.0 * SUM(CASE WHEN ship_mode IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_orders),
  'standardised to 4 labels';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'orders: exact duplicate lines removed (same order/product/values, different row_id)' AS check_name,
       (SELECT COUNT(*) FROM stg_orders) - (SELECT COUNT(*) FROM cln_orders) AS affected_rows
UNION ALL SELECT 'orders: missing postal_code (kept)', (SELECT SUM(dq_missing_postal_code) FROM cln_orders)
UNION ALL SELECT 'orders: postal_code with lost leading zero (repaired)',
       (SELECT COUNT(*) FROM stg_orders WHERE length(trim(postal_code)) = 4)
UNION ALL SELECT 'orders: sales with float artefacts (>2 dp, rounded)',
       (SELECT COUNT(*) FROM stg_orders WHERE length(split_part(sales, '.', 2)) > 2)
UNION ALL SELECT 'orders: ship_date < order_date', (SELECT COUNT(*) FROM stg_orders WHERE TRY_CAST(ship_date AS DATE) < TRY_CAST(order_date AS DATE))
UNION ALL SELECT 'orders: loss-making lines (profit < 0)', (SELECT SUM(is_loss_line) FROM cln_orders)
UNION ALL SELECT 'orders: sales outlier (> Q3 + 3*IQR, kept)', (SELECT SUM(is_sales_outlier_iqr3) FROM cln_orders)
UNION ALL SELECT 'orders: profit outside p1-p99 (kept)', (SELECT SUM(is_profit_extreme_p1_p99) FROM cln_orders)
UNION ALL SELECT 'products: product_id mapped to >1 product_name',
       (SELECT COUNT(*) FROM (SELECT product_id FROM dim_product GROUP BY product_id HAVING COUNT(*) > 1) x)
UNION ALL SELECT 'customers: customer_id with >1 name or segment',
       (SELECT COUNT(*) FROM (SELECT customer_id FROM cln_orders GROUP BY customer_id
                              HAVING COUNT(DISTINCT customer_name) > 1 OR COUNT(DISTINCT segment) > 1) x)
UNION ALL SELECT 'returns: duplicate rows collapsed to order grain', (SELECT COUNT(*) FROM stg_returns) - (SELECT COUNT(*) FROM cln_returns)
UNION ALL SELECT 'returns: returned orders not found in orders', (SELECT COUNT(*) FROM cln_returns WHERE order_id NOT IN (SELECT order_id FROM cln_orders))
UNION ALL SELECT 'orders: lines on returned orders', (SELECT SUM(returned_flag) FROM cln_orders)
UNION ALL SELECT 'RI: fact without customer', (SELECT COUNT(*) FROM fact_sales WHERE customer_key IS NULL)
UNION ALL SELECT 'RI: fact without product', (SELECT COUNT(*) FROM fact_sales WHERE product_key IS NULL)
UNION ALL SELECT 'RI: fact without geography', (SELECT COUNT(*) FROM fact_sales WHERE geo_key IS NULL)
UNION ALL SELECT 'RI: fact without ship mode', (SELECT COUNT(*) FROM fact_sales WHERE ship_mode_key IS NULL);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_sales.line_id unique' AS check_name, (SELECT COUNT(*) - COUNT(DISTINCT line_id) FROM fact_sales) AS failed_rows
  UNION ALL SELECT 'fact_sales.customer_key -> dim_customer', (SELECT COUNT(*) FROM fact_sales WHERE customer_key IS NULL OR customer_key NOT IN (SELECT customer_key FROM dim_customer))
  UNION ALL SELECT 'fact_sales.product_key -> dim_product', (SELECT COUNT(*) FROM fact_sales WHERE product_key IS NULL OR product_key NOT IN (SELECT product_key FROM dim_product))
  UNION ALL SELECT 'fact_sales.geo_key -> dim_geography', (SELECT COUNT(*) FROM fact_sales WHERE geo_key IS NULL OR geo_key NOT IN (SELECT geo_key FROM dim_geography))
  UNION ALL SELECT 'fact_sales.ship_mode_key -> dim_ship_mode', (SELECT COUNT(*) FROM fact_sales WHERE ship_mode_key IS NULL OR ship_mode_key NOT IN (SELECT ship_mode_key FROM dim_ship_mode))
  UNION ALL SELECT 'fact_sales.order_date_key -> dim_date', (SELECT COUNT(*) FROM fact_sales WHERE order_date_key NOT IN (SELECT date_key FROM dim_date))
  UNION ALL SELECT 'ship_date >= order_date', (SELECT COUNT(*) FROM fact_sales WHERE ship_date < order_date)
  UNION ALL SELECT 'discount between 0 and 0.8', (SELECT COUNT(*) FROM fact_sales WHERE discount < 0 OR discount > 0.8)
  UNION ALL SELECT 'sales > 0 and quantity > 0', (SELECT COUNT(*) FROM fact_sales WHERE sales <= 0 OR quantity <= 0)
  UNION ALL SELECT 'one manager per region', (SELECT COUNT(*) FROM (SELECT region FROM cln_people GROUP BY region HAVING COUNT(*) > 1) x)
  UNION ALL SELECT 'every region has a manager', (SELECT COUNT(*) FROM dim_geography WHERE regional_manager = 'Unassigned')
  UNION ALL SELECT 'fact sales reconcile to clean orders', (SELECT CASE WHEN ABS((SELECT SUM(sales) FROM fact_sales) - (SELECT SUM(sales) FROM cln_orders)) < 0.01 THEN 0 ELSE 1 END)
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Quality summary
-- MAGIC All assertions should be PASS.

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visualizations
-- MAGIC Run each cell, click **+ > Visualization** and configure as described. The same views are pre-built in `superstore_sales_dashboard.lvdash.json`.

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Profit by region
-- Bar: X = region, Y = profit (label margin_pct)
SELECT region, regional_manager, sales, profit, margin_pct FROM a_region_performance ORDER BY profit DESC;

-- COMMAND ----------

-- Visualization: Discount impact
-- Bar: X = discount_band, Y = margin_pct
SELECT discount_band, order_lines, sales, profit, margin_pct, loss_line_pct FROM a_discount_impact ORDER BY discount_band;

-- COMMAND ----------

-- Visualization: Profit by sub-category
-- Horizontal bar: Y = sub_category, X = profit
SELECT category, sub_category, sales, profit, margin_pct, avg_discount_pct FROM a_discount_by_subcategory ORDER BY profit;

-- COMMAND ----------

-- Visualization: Shipping modes
-- Bar: X = ship_mode, Y = orders (tooltip avg_ship_days, margin_pct)
SELECT ship_mode, orders, order_share_pct, avg_ship_days, margin_pct FROM a_ship_mode ORDER BY service_level_rank;

-- COMMAND ----------

-- Visualization: Monthly sales
-- Line: X = year_month, Y = sales
SELECT year_month, orders, sales, profit FROM a_monthly_sales ORDER BY year_month;

-- COMMAND ----------

-- Visualization: State profit
-- Horizontal bar: Y = state, X = profit
SELECT state, region, sales, profit, margin_pct FROM a_state_profit ORDER BY profit;
